baseurl = "http://www.example.com"
title = "Tillmann Mühlpfordt"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
  author = "Tillmann Mühlpfordt"
  info = "DevOps & Academia & Personal"
  description = "My personal website. Be my guest."
  keywords = "blog,developer,personal"
  #avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/timueh/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 4
  url = "https://de.linkedin.com/in/tillmann-muehlpfordt"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url = "projects/"